//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountType
    {
        public int DiscountTypeId { get; set; }
        public string DiscountCode { get; set; }
        public string DiscountType1 { get; set; }
    }
}
